# Site settings
title: Dan Gold
email: me@danielcgold.com
description: Iâ€™m a frontend engineer @charitywater. I am currently traveling with Remote Year. I also like emojis ğŸ™ƒğŸ»ğŸ¶ğŸ±ğŸƒğŸŒ…ğŸ’°.
baseurl: ""
url: "http://www.danielcgold.com"

# Build settings
markdown: kramdown

# Assets
sass:
  style: compressed

# Plugins
gems:
  - jekyll-sitemap
